# Custom playbook for EC2 setup and configure VM to run crud docker image
- name: Install Docker for restapi application
  hosts: crudservers
  become: true
  tasks:
    - name : Install system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - python3-setuptools
        update_cache: yes
        state: present

    - name: Add Docker apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install docker module for python
      pip:
        name: docker
        state: present
    
    - name: Install ECR credential helper
      apt:
        name: amazon-ecr-credential-helper
        state: present

    - name: Create directory for docker
      file:
        path: "/home/ubuntu/.docker/"
        state: directory

    - name: Add ECR cred. helper parameter
      copy:
        content: |
                  {
                        "credsStore": "ecr-login"
                  }
        dest: /home/ubuntu/.docker/config.json

    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present

    - name: Add the user 'ubuntu' to a group 'docker'
      user:
        name: ubuntu
        groups: docker
        append: yes
        state: present

    - name: Ensure docker service is up and working
      service:
        name: docker
        state: started

# Ensure ssh connection is no longer persistent so user is assigned to a group during next session/task
    - name: Reset ssh connection
      meta: reset_connection